language: ruby
branches:
  only:
  - jb-travis-ci
services:
- docker
before_install:
- docker pull mongo:3.4
- docker tag mongo:3.4 mongo:latest
- docker build -t single_cell_docker .
script:
- docker ps -a
