language: ruby
branches:
  only:
  - jb-travis-ci
services:
- docker
before_install:
- apt-get update && apt-get -y install curl unzip jq
- curl -O https://releases.hashicorp.com/vault/1.0.1/vault_1.0.1_linux_amd64.zip
- unzip vault_1.0.1_linux_amd64.zip
- mv vault /usr/local/bin
- vault login $VAULT_TOKEN
- docker pull mongo:3.4
- docker tag mongo:3.4 mongo:latest
- docker build -t single_cell_docker .
script:
- vault list $VAULT_SECRET_PATH
